### ISSUE TITLE
Install gplsrc prereqs on Centos

### ISSUE THREAD

**Issue by olemyk** [IBM/ibm-spectrum-scale-install-infra#193] opened 2020-08-09 11:30 UTC
When installing against Centos, the task " build | Install prereqs for building GPL from source"  is only checking RedHat os and not Centos. 

An easy fix is just adding  _RedHat OR Centos._
Or use Ansible_ value that cover both Centos And RedHat

And why are we using block for this task?

```
    - block:  ## when: rhel8 node
        - name: build | Install prereqs for building GPL from source
          dnf:
            name: "{{ scale_build_gplsrc_el8_prereqs }}"
            state: present
      when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS' and ansible_distribution_major_version == '8'
```

**Comment by olemyk** [comment] 2020-08-09 14:38
Looks like this is fixed in Pullrequest:  https://github.com/IBM/ibm-spectrum-scale-install-infra/pull/98

**Comment by rajan-mis** [comment] 2020-08-10 05:58
@olemyk Yes i added this fix with mixed os support code .thanks

**Comment by acch** [comment] 2020-08-17 08:33
We may link #98 to this issue so that the issue is closed once the PR gets merged...

![image](https://user-images.githubusercontent.com/11490209/90375340-1e28b080-e075-11ea-82e0-82b39369540f.png)

**Comment by olemyk** [comment] 2020-09-22 15:35
New method that use scale_rhel_distribution in branch staging_development:

**Comment by olemyk** [comment] 2020-09-24 08:31
Pull request:  [https://github.com/IBM/ibm-spectrum-scale-install-infra/pull/225] should fix this.

**Comment by acch** [comment] 2020-10-05 12:47
#225 got merged so this can be closed, I guess?

**Closed** 2020-10-06 13:36 UTC
